# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\x12\tinference\x1a\x1cgoogle/protobuf/struct.proto\"Q\n\x0f\x45valuateRequest\x12\x11\n\taudio_b64\x18\x01 \x01(\t\x12\x13\n\x0btarget_text\x18\x02 \x01(\t\x12\x16\n\x0ephoneme_format\x18\x03 \x01(\t\"\xa6\x01\n\x10\x45valuateResponse\x12\x33\n\x0fintelligibility\x18\x01 \x01(\x0b\x32\x1a.inference.Intelligibility\x12\x36\n\x11phonetic_analysis\x18\x02 \x01(\x0b\x32\x1b.inference.PhoneticAnalysis\x12%\n\x04meta\x18\x03 \x01(\x0b\x32\x17.google.protobuf.Struct\"<\n\x0fIntelligibility\x12\r\n\x05score\x18\x01 \x01(\x01\x12\x1a\n\x12word_accuracy_rate\x18\x02 \x01(\x01\"m\n\x10PhoneticAnalysis\x12\x15\n\rfluency_level\x18\x01 \x01(\t\x12\x15\n\rfluency_score\x18\x02 \x01(\x01\x12+\n\x05words\x18\x03 \x03(\x0b\x32\x1c.inference.WordPronunciation\"\xb0\x01\n\x11WordPronunciation\x12\x13\n\x0btarget_word\x18\x01 \x01(\t\x12\x15\n\rtarget_phones\x18\x02 \x03(\t\x12\x16\n\x0eproduced_phone\x18\x03 \x03(\t\x12\x0b\n\x03per\x18\x04 \x01(\x01\x12\x0b\n\x03gop\x18\x05 \x01(\x01\x12\x0b\n\x03ops\x18\x06 \x03(\t\x12\x1d\n\x15pronunciation_quality\x18\x07 \x01(\t\x12\x11\n\taudio_b64\x18\x08 \x01(\t2[\n\x14PronunciationService\x12\x43\n\x08\x45valuate\x12\x1a.inference.EvaluateRequest\x1a\x1b.inference.EvaluateResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EVALUATEREQUEST']._serialized_start=58
  _globals['_EVALUATEREQUEST']._serialized_end=139
  _globals['_EVALUATERESPONSE']._serialized_start=142
  _globals['_EVALUATERESPONSE']._serialized_end=308
  _globals['_INTELLIGIBILITY']._serialized_start=310
  _globals['_INTELLIGIBILITY']._serialized_end=370
  _globals['_PHONETICANALYSIS']._serialized_start=372
  _globals['_PHONETICANALYSIS']._serialized_end=481
  _globals['_WORDPRONUNCIATION']._serialized_start=484
  _globals['_WORDPRONUNCIATION']._serialized_end=660
  _globals['_PRONUNCIATIONSERVICE']._serialized_start=662
  _globals['_PRONUNCIATIONSERVICE']._serialized_end=753
# @@protoc_insertion_point(module_scope)
